### ISSUE TITLE
[Notice] Future Release Schedule and Invitation for New Maintainers

### ISSUE THREAD

**Issue by dvm-shlee** [BrkRaw/brkraw#110]
Dear brkraw community,

I hope this message finds you well. First and foremost, I would like to extend my apologies for the recent inactivity on this repository. I am relatively new to programming at the time I start this project and this project is my first foray into product development. The learning curve involved in maintaining a project and organizing a community has been steep, but incredibly valuable.

I have been incredibly fortunate that many of you, especially those in the animal neuroimaging research field, have actively contributed to this project. Your involvement has led to significant improvements, even during periods when I was less active.

I am grateful to @grandjeanlab, @gdevenyi and other colleagues for their diligent work on standardizing rodent fMRI. In line with their efforts, I intend to further organize this community to make it more compatible with the animal MRI field, as well as to enhance brkraw as a convenient tool for conversion and BIDS conversion.

In order to achieve these goals, I am proposing the following plan:

**New Maintainers**: I would like to extend an open invitation to anyone interested in contributing as a maintainer. This opportunity may be particularly beneficial for those with expertise in reviewing documents and revised code in specific areas such as DTI, MRS, Anatomical MRI, BIDS standard and more. Please do not hesitate to get in touch if you would like to join our team.

**Release Schedule**: To maintain consistency and ensure progress, I plan to adopt a regular release cycle. Minor updates will occur every four months, with major updates released annually. The first minor update, v0.4.0, is scheduled for August 1st, followed by v0.4.1 in December. Major updates will increment the second version number, and when our community members collectively agree that the software is stable and robust, we will launch v1.0.0.

**Project Management**: I intend to incorporate the use of GitHub's Project feature, which can be found [here](https://github.com/orgs/BrkRaw/projects/1). Once the team has reviewed an issue, it will be added to our Project's "To-Do" list. This will allow for open monitoring of our progress and provide visibility into when we expect new features to be implemented. This will foster greater transparency and collaboration within our community.

I believe these changes will greatly improve the maintenance of the project and our collaborative efforts. I look forward to hearing your thoughts and suggestions.

Best

**Comment by araikes** [comment]
Happy to help.

**Comment by jeremie-fouquet** [comment]
Hi! Glad to see this, thank you for putting this together. Also happy to help. I had not seen your post at the time of my latest pull request #119; I hope it can fit into this new Project management. If not, I'm happy to make it fit.

Looking forward to the next steps!

**Comment by Remi-Gau** [comment]
Can do some drive by contribution
