### ISSUE TITLE
Getting parameters from the reco file

### ISSUE THREAD

**Issue by timwahoo** [BrkRaw/brkraw#116]
Hi,

I was wondering if the reco parameter file is being read into pvobj and if it can return the reco parameters similar to the get_method() function

Thanks

**Comment by timwahoo** [comment]
Nevermind, I found it in pvObj. Can we add the changes so that the get_reco(scan_id, reco_id) is also in the Brukerloader object

**Comment by dvm-shlee** [comment]
Hi Timothy, its been a long time.
I finally finalized the codebase, and preparing the manuscript.

If you still using and working on reconstruction, we can discuss how we can wrap this project, and I can now provide clear instruction how to addon reconstruction to current 0.5.0a codebase

Thanks.
