### ISSUE TITLE
Failed EPI conversion to nifti

### ISSUE THREAD

**Issue by Gab-D-G** [BrkRaw/brkraw#12]
Hi,

I have tried the conversion to nifti on the following mouse EPI acquisition:

```
Paravision 5.1
--------------
UserAccount:	galdan
Date:		2019-08-07
Researcher:	MCH_MFC_058
Subject ID:	20190807_MCH_MFC_058
Session ID:	mfc
Study ID:	1
Date of Birth:	None
Sex:		male
Weight:		5 kg
Subject Type:	Human
Position:	Supine		Entry:	HeadFirst

[ScanID]	Sequence::Protocol::[Parameters]
[001]	FLASH (pvm)::01-TriPilot-multi::
	[ TR: 200 ms, TE: 3 ms, pixelBW: 500.80 Hz, FlipAngle: 30 degree]
    [01] dim: 2D, matrix_size: 256 x 256 x 15, fov_size: 40 x 40 (unit:mm)
         spatial_resol: 0.156 x 0.156 x 1.000 (unit:mm), temporal_resol: 25600.000 (unit:msec)
[003]	RARE (pvm)::04_TriPilot_RARE::
	[ TR: 2500 ms, TE: 33 ms, pixelBW: 183.11 Hz, FlipAngle: 180 degree]
    [01] dim: 2D, matrix_size: 256 x 256 x 3, fov_size: 19.2 x 19.2 (unit:mm)
         spatial_resol: 0.075 x 0.075 x 0.500 (unit:mm), temporal_resol: 80000.000 (unit:msec)
[004]	EPI (pvm)::grandjeanDG_epi_v1::
	[ TR: 1000 ms, TE: 15 ms, pixelBW: 4006.41 Hz, FlipAngle: 50 degree]
    [01] dim: 2D, matrix_size: 75 x 40 x 26 x 780, fov_size: 18.6851476050082 x 10 (unit:mm)
         spatial_resol: 0.249 x 0.250 x 0.500 (unit:mm), temporal_resol: 1000.000 (unit:msec)
[005]	FLASH (pvm)::grad_epi_T1_reg::
	[ TR: 20 ms, TE: 4.50 ms, pixelBW: 137.36 Hz, FlipAngle: 20 degree]
    [01] dim: 3D, matrix_size: 170 x 182 x 170, fov_size: 17 x 18.2 x 17 (unit:mm)
         spatial_resol: 0.100 x 0.100 x 0.100 (unit:mm), temporal_resol: 870400.000 (unit:msec)
```

I ran the following, and the EPI file wasn’t successfully converted:
```
~/Work/dev/brkraw$ brkraw tonii 20190807_MCH_MFC_058.UE1/
NifTi file is genetared... [20190807_MCH_MFC_058_1-01-1]
NifTi file is genetared... [20190807_MCH_MFC_058_1-03-1]
NoneType: None
Failed..
NifTi file is genetared... [20190807_MCH_MFC_058_1-05-1]
```
Any idea regarding the source of the issue?

A copy of the data can be found here https://drive.google.com/drive/folders/1hcXVsyeTWRcK76OJ1VNQtAXdfJ91vBWf?usp=sharing

**Comment by dvm-shlee** [comment]
@Gab-D-G Thank you for sharing the data, I will check and let you know what could be an issue.

**Comment by dvm-shlee** [comment]
@Gab-D-G This seems unusual error I've never had. The reason is you have an inconsistent rescale value for each slide. Is it the version beyond Paravision 6.01 or do you have a particular setup on datatype? (default reconstruction option?)

**Comment by gdevenyi** [comment]
This is Paravision 5.1, and we have adjusted the reconstruction at least to remove the percentile clipping because it was messing up the full intensity range of the EPI. I wouldn't consider the value "inconsistent" its just every single timeslice is rescaled to maximize the data range. I think the converter should probable handle this properly.

**Comment by gdevenyi** [comment]
I wonder if --ignore-rescale would allow this to convert in the meantime.

**Comment by dvm-shlee** [comment]
@gdevenyi Yes, I think I can handle this. Thank you for your comment. If this is data for fMRI, the scale needs to be properly applied because rescaling each frame differently changes the timecourse.

**Comment by dvm-shlee** [comment]
@Gab-D-G Until I'm making an update, if you need urgent conversion, please use python API as below.

```python
import brkraw as br
raw = br.load('<data folder name>')
raw.get_niftiobj(4, 1, slope=True).to_filename('<output_filename>')
```

This will convert data after rescale using slope value.

**Comment by Gab-D-G** [comment]
Great, thanks a lot!

**Comment by dvm-shlee** [comment]
@Gab-D-G Sorry for delaying on this! The issue has resolved from v0.3.4. 
Please let me know if you have any issues regarding this update.

**Comment by Gab-D-G** [comment]
The conversion is working perfectly now. Thanks a lot for addressing this!

**Comment by Gab-D-G** [comment]
As a follow-up to this, I tried the conversion to BIDS format on the same dataset (in raw/20190807_MCH_MFC_058.UE1) and ran into the following error
```
(bruker_converter) gabriel@gabriel-XPS-13-7390:~/Work/dev/brkraw$ brkraw bids_convert raw/ bids_info.xlsx -j bids_info.json -o bids_out/
Inspect input BIDS datasheet...
Converting 20190807_MCH_MFC_058.UE1...
NoneType: None
Traceback (most recent call last):
  File "/home/gabriel/miniconda3/envs/bruker_converter/bin/brkraw", line 8, in <module>
    sys.exit(main())
  File "/home/gabriel/miniconda3/envs/bruker_converter/lib/python3.7/site-packages/brkraw/scripts/brkraw.py", line 489, in main
    build_bids_json(dset, sub_row, fname, json_fname, slope=slope, offset=offset)
  File "/home/gabriel/miniconda3/envs/bruker_converter/lib/python3.7/site-packages/brkraw/lib/utils.py", line 580, in build_bids_json
    metadata=ref, condition=condition)
  File "/home/gabriel/miniconda3/envs/bruker_converter/lib/python3.7/site-packages/brkraw/lib/loader.py", line 509, in save_json
    json_obj = self._parse_json(scan_id, reco_id, metadata)
  File "/home/gabriel/miniconda3/envs/bruker_converter/lib/python3.7/site-packages/brkraw/lib/loader.py", line 490, in _parse_json
    raise UnexpectedError('Unexpected phase encoding direction in PV5.1.')
shleeh.errors.UnexpectedError: Unexpected phase encoding direction in PV5.1.
```
The .xlsx and .json files were obtained by running 
```
(bruker_converter) gabriel@gabriel-XPS-13-7390:~/Work/dev/brkraw$ brkraw bids_helper raw bids_info -j
```
It seems to ignore the error when I run the conversion using tonii_all -b option, but this option doesn't take care of the file naming
```
(bruker_converter) gabriel@gabriel-XPS-13-7390:~/Work/dev/brkraw$ brkraw tonii_all raw -o out -b
NoneType: None
Unexpected phase encoding direction in PV5.1.
NoneType: None
Unexpected phase encoding direction in PV5.1.
20190807_MCH_MFC_058.UE1 is converted...
```
Can I get support on this issue?

**Comment by dvm-shlee** [comment]
@Gab-D-G  I will check the issue! Thank you for the report!

**Comment by dvm-shlee** [comment]
@Gab-D-G Sorry about late to solve this issue. The issue occurs during metadata parsing for JSON, and multiple phase encoding directions caused this. I just remove the exception on the code and updated it to parsing the values for each slice packages. So the error will not show up for future versions.

Currently, due to the paper review, I'm planning to update solutions for the all current issue on the one release version, until I released the patch version, would you mind to install the package through GitHub repo?

If you have any other issues regarding this update, please let me know!
