### ISSUE TITLE
Regular Bruker recon tools from raw fid

### ISSUE THREAD

**Issue by timwahoo** [BrkRaw/brkraw#148]
There are many normal bruker sequences that  are easy to reconstruct. why not have a image reconstruction pipeline for these commonly used sequences?

**Comment by dvm-shlee** [comment]
Hi @timwahoo,

That's a fantastic suggestion! Could you share your pipeline for integrating brkraw into image reconstruction? I'm particularly interested in how it facilitates FID reconstruction directly from raw data without needing direct access to the scanner. This could be a very useful capability for our work.

Thanks in advance!

**Comment by dvm-shlee** [comment]
Pull request #152 has been merged to the project and this feature is added.
