### ISSUE TITLE
GUI Unable to open PV7 and PV360 zip files

### ISSUE THREAD

**Issue by timwahoo** [BrkRaw/brkraw#154]
PV360 and PV7 files will not appear when trying to open its corresponding zip file.

**Comment by gdevenyi** [comment]
Hi,

Can you supply an example dataset for testing?

**Comment by timwahoo** [comment]
![Screenshot from 2024-02-13 13-04-48](https://github.com/BrkRaw/brkraw/assets/139504215/455efe4d-0c8d-43b6-b8cf-7a72990a68d0)

I think the problem could just be the ending for pvdataset

**Comment by dvm-shlee** [comment]
Could you share some sample data on Google Drive? The Brkraw tool uses the PyZip module and checks it by inputting it into the Pvobj class. There might be some differences in the file structure or the method used to compress the raw data.

**Comment by timwahoo** [comment]
For 360, I think the problem is string matching (which is still relevant for using the GUI with newer datasets. But I was trying a dataset from Universidad Nacional Autonoma de Mexico (his data zip file is in there pv7) that I had problems with. It could be problems with the zip format.

**Comment by dvm-shlee** [comment]
@timwahoo Have you tried extract the file into folder using unzip command?

**Comment by timwahoo** [comment]
I tried to unzip it and then it worked. thanks
