### ISSUE TITLE
Missing buttons and image preview display when running in Apptainer

### ISSUE THREAD

**Issue by pcamach2** [BrkRaw/brkraw#159]
**Describe the bug**
I am trying to run the brkraw GUI using an Apptainer image that my colleagues can use on some shared linux machines. The container builds and I am able to open a dataset, but the image preview section and the buttons to convert the dataset are not visible in the GUI. The window also does not scale, but that may be a display setting on my end since it does not scale with a native installation of brkraw.

**To Reproduce**
1. Build Apptainer (v1.3.0) image using the following definition file:
```
Bootstrap: docker
From: python:3.11

%post
	apt-get update && apt-get upgrade -y && apt-get install git
	apt-get install -y python3-tk
	pip install shleeh nibabel numpy pandas pillow tqdm openpyxl xlrd        
        pip install git+https://github.com/brkraw/bruker

%runscript
    echo "Starting BrkRaw GUI"
    echo "To view an existing directory, bind input directory to /datain, output directory to /dataout"
    exec bash -c "if [ -d /datain ] && [ -d /dataout ]; then brkraw gui -i /datain -o /dataout; else brkraw gui; fi"
```
  
The build command here is:
```
apptainer build brkraw-v0.3.11.sif bruker_gui.def
```

2. Run the container with the relevant data directories bound and access to the X11 display: 
```
APPTAINER_ENVDISPLAY=${DISPLAY} apptainer exec -B /tmp/.X11-unix:/tmp/.X11-unix,/home/pcamach2/dev/singularity/bruker/test:/datain,./output:/dataout brkraw-v0.3.11.sif brkraw gui
```
3. Click to open a `.zip` file containing the raw data.
4. See warning printed in terminal and incomplete GUI window (see screenshots):
```
/usr/local/lib/python3.11/site-packages/brkraw/lib/loader.py:951: UserWarning: Unexpected version[VisuVersion];8
  warnings.warn('Unexpected version[VisuVersion];{}'.format(version), UserWarning)
```

**Expected behavior**
The preview window and all buttons needed to perform conversion should be visible in the GUI when running via Apptainer.

**Screenshots**
I covered the names of scans and the preview image since the scan data is from an internal WIP.

Here is the window from Apptainer:
![redacted_screen_apptainer](https://github.com/BrkRaw/brkraw/assets/49655443/1434ca17-92f4-4395-8888-c217088e09f0)

When running from my local install, the display looks as expected:
![redacted_screen](https://github.com/BrkRaw/brkraw/assets/49655443/b5b27f0d-8613-414c-8929-5c2a7cdc8062)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Window system: X11
 - Version: brkraw version 0.3.11
 - Python version: 3.11

**Additional context**
I am running with Apptainer version 1.3.0 on my host machine. I tried opening X window access with `xhost +`, but this did not affect Apptainer GUI issue. I also tried using earlier versions of brkraw with a python 3.7 base image and SimpleITK, but this failed also.

When running from the local install (python 3.11), the VisuVersion warning is the same so I don't believe that is the main issue here. 

Thanks in advance for the help!

**Comment by timwahoo** [comment]
Hi @pcamach2, 

That's interesting, I'm not too familiar with Apptainer but following your build commands I was unable to replicate the problem, the gui seems to work on my end. Although, I seem to have issues with the convert button not being able to save images.

I had brkraw v3.11.0 added to neurodesktop (which also uses singularity containers) but it didn't have that problem either. 

Tim

**Comment by pcamach2** [comment]
Hi @timwahoo,

Thank you for looking into this! Did you build the Apptainer image on an Ubuntu 22.04LTS machine? 

Regarding neurodesktop, was the Singularity image built from a Docker image? If so, which Dockerfile did you use?

Thanks,
Paul

**Comment by timwahoo** [comment]
Hi @pcamach2 ,

Yes, my system is on Ubuntu 22.04.4 LTS. I'm not too sure what build file is on neurodesktop since neurocontainers use neurodocker to generate a docker buildfile. But an alternative is to download their singularity container using this command 

```
curl -X GET https://objectstorage.us-ashburn-1.oraclecloud.com/n/sd63xuke79z3/b/neurodesk/o/brkraw_0.3.11_20240320.simg -o
```
Then probably use this command to test the container.
```
apptainer exec brkraw_0.3.11_20240320.simg brkraw gui -i {YOUR_DATA_PATH} 
```
Hope this helps.

Tim

**Comment by pcamach2** [comment]
Hi @timwahoo,

Thank you for the information! I built a new Apptainer image from a Docker image created with the `Dockerfile.dev` in this repo and the GUI opens as expected on our lab machines (Ubuntu 20.04.6 LTS), however the convert button still does not work.

For security and reproducibility purposes, I would prefer not to download and run an existing externally created image on lab hardware. 

I think the graphics issue is probably a setting on my build machine, so perhaps we should close this issue and open one for only the convert button bug.

Thanks,
Paul

**Comment by timwahoo** [comment]
Hi @pcamach2 ,

Sounds good.

Tim
