### ISSUE TITLE
Feature Request: Add override settings for orientation information

### ISSUE THREAD

**Issue by gdevenyi** [BrkRaw/brkraw#26]
It is possible for an operator to set orientation (and subject type, see #25 ) incorrectly such that conversion does not work properly. I'd like to request options to override the detected orientation to allow conversion to work properly.

**Comment by gdevenyi** [comment]
Ref #10

**Comment by dvm-shlee** [comment]
@gdevenyi I think it would be straight forward for 'tonii' function but probably need to mine some idea how to override specific data in case of tonii_all and bids_convert functions. I will let you know if I figure out the solution. But please let me know if you have comments or any suggestion. Thanks!

**Comment by gdevenyi** [comment]
I'm okay with it simply being a global setting for tonii_all and bids_convert.
