### ISSUE TITLE
docker version of brkraw

### ISSUE THREAD

**Issue by ycAbout** [BrkRaw/brkraw#39]
I recently has put a couple issues. I currently work with Dr. Gabriel A. Devenyi @gdevenyi on a project that potentially involves brkraw bids converter.
I think a docker version of brkraw would be helpful, given that someone don't have to worry about dependency conflict with other project (or as an alternative to python venv). 
I made a simple docker version:
https://hub.docker.com/r/ycabout/brkraw
Feel free to ignore this.

**Comment by dvm-shlee** [comment]
@ycAbout @gdevenyi 
Thank you for working on this!
I'm currently checking all the issues, and inspecting my code for further improvement including all your suggestion.
Once I organized some to-do lists, I hope to discuss with you the best way to make this project more readable, robust, and solid.
(including organization of dev team who can contribute fixing the issue and manage the pull requests)

Could you please reply to this thread how do you think?

Thank you!

**Comment by gdevenyi** [comment]
I'm all in for continuing to help. I swear I can sling code and eventually will...

**Comment by ycAbout** [comment]
Thanks. I think it is a good idea. FYI: currently I am working on the bids converter part and has done some work which hasn't been included in the pull request yet. I will have vacation and get back to it in May.

**Comment by dvm-shlee** [comment]
@gdevenyi @ycAbout Cool! Thank you so much you all, I'm really excited to work with you!
