### ISSUE TITLE
bids converter output file should not be xlsx

### ISSUE THREAD

**Issue by ycAbout** [BrkRaw/brkraw#42]
This is related to the discussion of issue #41
Gabriel @gdevenyi mentioned that for bids converter, [the documentation here](https://brkraw.github.io/docs/gs_bids.html), 
an excel file should not be produced and used, it should be a csv file.
I agree with him, and feels maybe another json file instead of .xlsx or csv might be a good choice.

**Comment by dvm-shlee** [comment]
I will update to use csv file then, the reason I choose the xlsx was for our lab member.
but agree that the csv will be the better option

**Comment by dvm-shlee** [comment]
brkraw now support csv, tsv, xlsx, (default csv)
