### ISSUE TITLE
[brkraw.py] Consider break main function in brkraw.py script into multiple shorter functions

### ISSUE THREAD

**Issue by ycAbout** [BrkRaw/brkraw#46]
The main function is way too long in brkraw.py. To increase readability and maintainability, it should be break down into multiple shorter functions. If you don't believe me, please google search "best practice function length"

**Comment by dvm-shlee** [comment]
Thank you for your suggestion,
The brkraw code was kind of built by practical reason, then have not been organized.
I will work on it to modulate it into small fundamental functions for more readibility.

Also thank you for the suggestion on the resource as well, I will check it.

**Comment by ycAbout** [comment]
It you plan to work on it in next three weeks, could you please leave the bids helper and bids converter parts for now? I have made some changes there and don't want to result in unnecessary code conflicts. :) Thanks.
