### ISSUE TITLE
Error in running command-line commands

### ISSUE THREAD

**Issue by suhyun417** [BrkRaw/brkraw#48]
This could be a very basic Python question, as I don't know very well about Python, but whenever I run the command-line commands I got an error message of some sort.
For example, below is the error message I get when I run "brkraw info":
![image](https://user-images.githubusercontent.com/7525608/114885684-e412d880-9dd4-11eb-8ca6-f4d1c422bac9.png)

Also, the "brkraw gui" opens the GUI, but when I try to convert a scan, it gives out an error like below:
![image](https://user-images.githubusercontent.com/7525608/114885889-16bcd100-9dd5-11eb-8edc-7080a179b8bb.png)

If anyone could help me with this, I would greatly appreciate.

Thanks,
Soo Hyun

**Comment by dvm-shlee** [comment]
@suhyun417 Hi, sorry for the late response.
It is maybe the latest 'released' version in PyPI has those issue,
Have you tried the latest 'GitHub' version?

could you try re-install package using
pip install git+https://github.com/brkraw/bruker

then test if the issue still occurs?

**Comment by suhyun417** [comment]
Hi, thank you for the response. I re-installed the 'GitHub' version as suggested, but had no luck- I'm getting the same error. FYI, the re-installation appears to be done well by and large. 
![image](https://user-images.githubusercontent.com/7525608/116100934-6758e780-a67b-11eb-969b-d45fe14c9286.png)

**Comment by dvm-shlee** [comment]
@suhyun417 Could you provide a sample dataset that contains the same acquisition protocol? If the data you are trying to convert is fine for exposure to external, it would be best to correct the issue.

**Comment by dvm-shlee** [comment]
@suhyun417 the issue might already been resolved, If you still having same issue, please use `bruker-0.3.8rc1` Thank you
