### ISSUE TITLE
[Configuration] configurable replacement on underscore and hyphen in participant ID and session ID

### ISSUE THREAD

**Issue by ycAbout** [BrkRaw/brkraw#52]
@gdevenyi gets full credit of this feature request. 

General speaking, underscore ("_") and hyphen ("_") should be avoided in participant ID and session ID in your datasets if you are considering converting to bids format. However, in reality, there is some cases that do contain underscore and hyphen in participant ID and session ID. 
brkraw bids_concert replaces those character with "Underscore" and "Hyphen", but make the replacement configurable would be better.

**Comment by dvm-shlee** [comment]
The pull request related to this issue has been merged. Thank you!

**Comment by gdevenyi** [comment]
This feature I believe hasn't been merged. This is a followup on #50 to make the substitution configurable, rather than hard-coded.
