### ISSUE TITLE
[bids converter] Remove .bamt files in bids output

### ISSUE THREAD

**Issue by ycAbout** [BrkRaw/brkraw#58]
BIDS standard does not support .bmat file, and there is no plan for them to support the type given that, BIDS already supports bval & bvec files and these two and .bmat are same thing. (Are they the same thing?)

See also issue
https://github.com/bids-standard/bids-specification/issues/770

**Comment by gdevenyi** [comment]
Notes on file formats, http://brainsuite.org/processing/diffusion/file-formats/

**Comment by dvm-shlee** [comment]
@ycAbout @gdevenyi Hi, thank you for pointing out. Actually, I'm not familiar with the DTI preprocessing, so just added all function to extract all possible parameter from the header that I can search from google. BTW, I doubt the code I wrote whether it could correctly generate the bval and bvec. Could you provide some sample DTI data (raw data) with an ideally converted nifti file with the bval, bvec? Some gradient direction and animal orientation-related things were not clear to me when I coded that.

**Comment by gdevenyi** [comment]
> Could you provide some sample DTI data (raw data) with an ideally converted nifti file with the bval, bvec? 

Do you mean some human data?

**Comment by dvm-shlee** [comment]
> > Could you provide some sample DTI data (raw data) with an ideally converted nifti file with the bval, bvec?
> 
> Do you mean some human data?

Oh no, any data collected from Bruker scanner? Just in case if you have any

**Comment by gdevenyi** [comment]
I think there's a set in what I sent you ☺️

**Comment by ycAbout** [comment]
If this also helps: 
For a couple bids output files such as 
`****run-02_dwi.nii.gz`
it does not pass the bids validator with the following error:
`The number of volumes in this scan does not match the number of volumes in the corresponding .bvec and .bval files.`

**Comment by dvm-shlee** [comment]
@ycAbout does it the one converted from the test dataset you had shared to me? I will take a look.

**Comment by gdevenyi** [comment]
@ycAbout is working with the same files I sent to you @dvm-shlee

**Comment by dvm-shlee** [comment]
patched on de6cb1e69bc10d101db0fcabe88179ede778335b
