### ISSUE TITLE
[naming] consider change repository name from bruker to brkraw

### ISSUE THREAD

**Issue by ycAbout** [BrkRaw/brkraw#61]
It seems brkraw is used everywhere, however, the repository name is bruker. This seems a bit confusing. It might be better to change the repository name to brkraw and to be consistent along the way.

**Comment by gdevenyi** [comment]
:+1: to this. it is indeed confusing

**Comment by dvm-shlee** [comment]
I think it is good suggestion, I just try to take the good name early for the python package and name the actual package later,;D

**Comment by dvm-shlee** [comment]
Changed it! But please let me know if the change of folder name causes any issues!

@ycAbout I'm considering making this more open-source, so please let me know if you have any other suggestions! I'm learning!

I will set some progress and milestone documents for the group.

**Comment by ycAbout** [comment]
Great! @dvm-shlee  It's very nice to have such a project so people can use it!

**Comment by gdevenyi** [comment]
> Changed it! But please let me know if the change of folder name causes any issues!

Thankfully github actually sets up redirects internally, so everything keeps working for clones etc :) 👍🏻
