### ISSUE TITLE
[BIDS converter] way to handle session in output

### ISSUE THREAD

**Issue by ycAbout** [BrkRaw/brkraw#62]
Currently in bids converter, if you remove session in datasheet, no session will be appeared in output. Otherwise, it is based on whether there is multiple session. Session only appears with multiple session. I think it is helpful to be able to include session info even for single session. 
I'm working on it to figure out a way.

**Comment by dvm-shlee** [comment]
I think I just made to not create the session when all session name is same. Maybe just need to make condition as bellow?

If session id is None -> single session.
If session id exists -> multi session

**Comment by ycAbout** [comment]
Hi @dvm-shlee , Great! I think we are on the same page, I already made a PR for it. 
If session id is None -> single session --> session not appear in output.
If session id exists -> multi session --> session appear in output, and multi_session should be include_session.
