### ISSUE TITLE
xlrd 2.0.1 Dropped Supports of XLSX

### ISSUE THREAD

**Issue by cecilyen** [BrkRaw/brkraw#78]
**Describe the bug**
I just installed brkraw on CentOS 7. Then, I tried to run BIDS convertor. brkraw reported "xlrd.biffh.XLRDError: Excel xlsx file; not supported"

**Desktop (please complete the following information):**
 - OS: CentOS 7.9
 - Python: 3.6.8
 - xlrd: 2.0.1

**Additional context**
I found xlrd dropped XLSX support from 2.0.0 last year. To solve this, one must uninstall xlrd>2.0.0 and install xlrd==1.2.0 via pip3.
A better solution is to have brkraw using openpyxl instead of xlrd.

**Comment by gdevenyi** [comment]
Related, don't use XLS at all, https://github.com/BrkRaw/brkraw/issues/42

**Comment by cecilyen** [comment]
> Related, don't use XLS at all, #42

XLS is a proprietary format, which is not good to exchange information. But, I think either CSV or XLSX is fine.

**Comment by dvm-shlee** [comment]
@gdevenyi @cecilyen I'm actually considering it would be better to use HTML5 based GUI through the web browser, to handle the data. While I prepare some new solutions, I will make it CSV compatible.

**Comment by gdevenyi** [comment]
> HTML5 based GUI

GUIs are fine and all, but the workflows I use brkraw for are command-line and preferably automated, I'd like to see brkraw move in the direction of https://github.com/nipy/heudiconv for automation

**Comment by dvm-shlee** [comment]
@gdevenyi @cecilyen `bids_helper` now supports CSV, TSV, and XLSX
I added optional argument --format (-f) option for `bids_helper` command.

So the conduction made by
1. if the user provided an extension on output filename, it will use that format time among (csv, tsv, xlsx)
2. if the user did not provide an extension, it will use default file format, csv
3. user can specify which format to be used for helper datasheet among csv, tsv, xlsx via '--format', '-f' option

Of note, csv format is literally 'comma-separated' and tsv is 'tap-separated'. so if you want to use a tap-separated datasheet, tsv need to be used.

Please let me know if you experience any additional issues with this update. If not, I will close this comment.
Thank you!
