### ISSUE TITLE
JSON updates

### ISSUE THREAD

**Issue by araikes** [BrkRaw/brkraw#92]
**Is your feature request related to a problem? Please describe.**
@dvm-shlee,

I was editing my local JSON template and wanted to include information about the number of EPI segments for our diffusion scans. We had to do a lot of trouble shooting so knowing the number of segments for a particular scan would be helpful. This field is in the "methods" file and is `##$NSegments=2 or 4 or whatever`. If I put `"Segments": "NSegments"` in the JSON template, it just puts "NSegments" in the output JSON. 

Is there a there a way to get it to output the number of segments rather than the string "NSegments"? Other custom fields, like the number of diffusion directions `PVM_DwDiffDir` works fine.

**Comment by dvm-shlee** [comment]
@araikes please find the change I made to the code on the below.
https://github.com/BrkRaw/brkraw/pull/94/commits/3b871e28734c4b20732d75fd46289ae9ebd58c4e

Originally the metadata was parsed based on the prefix of the key string. But it will now check first from acqp, method, or visu_pars, then return the value from the one have the key value.

If this change does not solve your issue, please let me know.
